[workspace]
members = [
    "audio-engine",
    "backend",
    "shared",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"
